### ISSUE TITLE
requirements.txt is missing in pypi source

### ISSUE THREAD

**Issue by milahu** [matan1008/pygnuutils#11]
```
FileNotFoundError: [Errno 2] No such file or directory: '/build/pygnuutils-0.0.6/requirements.txt'
```

**Comment by matan1008** [comment]
Could you please supply some more context?

**Comment by milahu** [comment]
https://pypi.org/project/pygnuutils/

```
wget https://files.pythonhosted.org/packages/b5/e5/d62b0cb91a97007032e0ab4442b28f5ae954076f32accbc6a9f2da67aabc/pygnuutils-0.0.6.tar.gz
tar tf pygnuutils-0.0.6.tar.gz | grep -e requirements.txt -e setup.py
# pygnuutils-0.0.6/setup.py
```

`pygnuutils-0.0.6/requirements.txt` is missing

**Comment by matan1008** [comment]
Packages don't need requirements.txt, [see here](https://packaging.python.org/en/latest/tutorials/packaging-projects/#creating-the-package-files)

**Comment by milahu** [comment]
but setup.py is in the package

https://github.com/matan1008/pygnuutils/blob/e04d825a0a997bb0b7cb92697b62f40864242a5e/setup.py#L13

so... ideally migrate to pyproject.toml
